services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: "bd&testlocal123"
      MYSQL_DATABASE: my_test_degusta_box
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
