tasks:
  path: /
  controller: App\Infrastructure\Controller\TaskController::getAllTasks

start_task:
  path: /task/start
  controller: App\Infrastructure\Controller\TaskController::getStartTask

end_task:
  path: /task/end
  controller: App\Infrastructure\Controller\TaskController::getEndTask
